---
title: "Case Study:1"
author: "Ramesh Naidu"
date: "3/3/2021"
output:
   html_document: default
---

```{r setup, include=FALSE}
## Install Packages Once (Watch for Errors)
knitr::opts_chunk$set(echo = TRUE,error=FALSE,message = FALSE,warning = FALSE)
# install.packages("ggplot2")
# install.packages("scales")
# install.packages("dplyr" )
# install.packages("forecast")
# install.packages("rmarkdown")
#install.packages("DT")
#install.packages(janitor)
## Load Library
library(ggplot2)
library(scales)
library(dplyr)
library(forecast)
library(janitor)

```
```{r}
rm(list=ls())

df <- read.csv("./StatsServicesExport.csv") %>% remove_empty()
df$SampleDate <- as.Date(df$SampleDate)
df$DateofBirth <- as.Date(df$DateofBirth)
df$USDate <- as.Date(df$USDate)

```

### Count of Smoking/Non and Unknown

```{r}
df$SmokingGroup <- ifelse((df$Smoking=="0"), "No","Unknown")
df$SmokingGroup <- ifelse((df$Smoking=="1"), "Yes",df$SmokingGroup)


smokers <- df %>% group_by(SmokingGroup) %>% summarise(
  Count = n()
) 
```

```{r}
smokers <- as.data.frame(smokers)
ggplot(smokers) + geom_col(aes(x=SmokingGroup,y=Count)) + scale_y_log10(labels=comma) +
  labs(title="Count of Smoker/non-smoker",y="Total Number of Women(log10)")

```

### Plot of Ethnicity

```{r}
#Ethnic Group classification
df$EthnicGroup = ifelse((df$Ethnicity=="51"), "Afro-Caribbean","Unknown")
df$EthnicGroup = ifelse((df$Ethnicity=="52"), "Asian",df$EthnicGroup)
df$EthnicGroup = ifelse((df$Ethnicity=="53"),"Caucasian",df$EthnicGroup)
df$EthnicGroup = ifelse((df$Ethnicity=="0"),"Default",df$EthnicGroup)
df$EthnicGroup = ifelse((df$Ethnicity=="54"),"Oriental",df$EthnicGroup)
df$EthnicGroup = ifelse((df$Ethnicity=="60"),"Other",df$EthnicGroup)
```

```{r}
ethnic <- df %>% select(EthnicGroup) %>% group_by(EthnicGroup) %>%
  summarise(Count = n()) 
ethnic <- as.data.frame(ethnic)
ggplot(ethnic) + geom_col(aes(reorder(EthnicGroup,Count),y=Count)) + coord_flip() +
  scale_y_log10(labels=comma) + labs(title="Count by Ethnic Group",y="Ethnic",x="Count(log10)")

```

####  Maternal Weight Distribution

```{r}
df$GAweek <-  floor(df$GestationalAge/7)
df$Weight <- floor(df$Weight/10) *10 
```
```{r}
GAP <- df %>% group_by(GAweek) %>% summarise(
  Median = median(Weight),
  Mean = mean(Weight),
  Sd = sd(Weight),
  Min = min(Weight),
  Max = max(Weight)

) %>%  filter(Median >0)

```
```{r}
GAP <- as.data.frame(GAP)
GAP  %>% DT::datatable() %>%   DT::formatRound(2:6,digits=1)


```

```{r}

ggplot(df) + geom_histogram(aes(x=Weight),bin=10) +
  labs(title=" Maternal Weight Distribution")
```

#### Count of Number of Gestational Weeks 

```{r}
xtabs(~df$GAweek) 
```

#### Orignal HCGb MOMs by Gestational Week

```{r}
ggplot(df) + geom_col(aes(x=GAweek,y=HCGbMoM,col=HCGbMoM)) +
  scale_y_continuous(labels=comma)
  labs(title="HCGb MOMs by Gestational Week") 
```

```{r}
df %>% 
  group_by(GAweek = as.factor(GAweek)) %>% 
  summarise(min_hcgbmom = min(HCGbMoM), max_hcgbmom = max(HCGbMoM)) %>% 
  ggplot() + 
  geom_errorbar(
    aes(x = GAweek, ymin = min_hcgbmom, ymax = max_hcgbmom),
    width = .2
  )
```



